/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsApiKeyRouteImport } from './routes/docs/api-key'
import { Route as DocsFetchSubdomainsRouteImport } from './routes/docs/fetch-subdomains'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiKeyRoute = DocsApiKeyRouteImport.update({
  id: '/docs/api-key',
  path: '/docs/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFetchSubdomainsRoute = DocsFetchSubdomainsRouteImport.update({
  id: '/docs/fetch-subdomains',
  path: '/docs/fetch-subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/docs/api-key' | '/docs/fetch-subdomains' | '/api/public/hooks/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/docs/api-key' | '/docs/fetch-subdomains' | '/api/public/hooks/scan'
  id:
    | '__root__'
    | '/'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/api/public/hooks/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsApiKeyRoute: typeof DocsApiKeyRoute
  DocsFetchSubdomainsRoute: typeof DocsFetchSubdomainsRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-key': {
      id: '/docs/api-key'
      path: '/docs/api-key'
      fullPath: '/docs/api-key'
      preLoaderRoute: typeof DocsApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/fetch-subdomains': {
      id: '/docs/fetch-subdomains'
      path: '/docs/fetch-subdomains'
      fullPath: '/docs/fetch-subdomains'
      preLoaderRoute: typeof DocsFetchSubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsApiKeyRoute: DocsApiKeyRoute,
  DocsFetchSubdomainsRoute: DocsFetchSubdomainsRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
