/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as DocsApiKeyRouteImport } from './routes/docs/api-key'
import { Route as DocsFetchSubdomainsRouteImport } from './routes/docs/fetch-subdomains'
import { Route as DomainDomainRouteImport } from './routes/domain.$domain'
import { Route as ProgramSlugRouteImport } from './routes/program.$slug'
import { Route as ApiPublicExportRouteImport } from './routes/api/public/export'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiKeyRoute = DocsApiKeyRouteImport.update({
  id: '/docs/api-key',
  path: '/docs/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFetchSubdomainsRoute = DocsFetchSubdomainsRouteImport.update({
  id: '/docs/fetch-subdomains',
  path: '/docs/fetch-subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainRoute = DomainDomainRouteImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSlugRoute = ProgramSlugRouteImport.update({
  id: '/program/$slug',
  path: '/program/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportRoute = ApiPublicExportRouteImport.update({
  id: '/api/public/export',
  path: '/api/public/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/programs': typeof ProgramsRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/programs': typeof ProgramsRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/programs': typeof ProgramsRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/new'
    | '/programs'
    | '/stats'
    | '/updates'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/domain/$domain'
    | '/program/$slug'
    | '/api/public/export'
    | '/api/public/hooks/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/new'
    | '/programs'
    | '/stats'
    | '/updates'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/domain/$domain'
    | '/program/$slug'
    | '/api/public/export'
    | '/api/public/hooks/scan'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new'
    | '/programs'
    | '/stats'
    | '/updates'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/domain/$domain'
    | '/program/$slug'
    | '/api/public/export'
    | '/api/public/hooks/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  ProgramsRoute: typeof ProgramsRoute
  StatsRoute: typeof StatsRoute
  UpdatesRoute: typeof UpdatesRoute
  DocsApiKeyRoute: typeof DocsApiKeyRoute
  DocsFetchSubdomainsRoute: typeof DocsFetchSubdomainsRoute
  DomainDomainRoute: typeof DomainDomainRoute
  ProgramSlugRoute: typeof ProgramSlugRoute
  ApiPublicExportRoute: typeof ApiPublicExportRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-key': {
      id: '/docs/api-key'
      path: '/docs/api-key'
      fullPath: '/docs/api-key'
      preLoaderRoute: typeof DocsApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/fetch-subdomains': {
      id: '/docs/fetch-subdomains'
      path: '/docs/fetch-subdomains'
      fullPath: '/docs/fetch-subdomains'
      preLoaderRoute: typeof DocsFetchSubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$slug': {
      id: '/program/$slug'
      path: '/program/$slug'
      fullPath: '/program/$slug'
      preLoaderRoute: typeof ProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/export': {
      id: '/api/public/export'
      path: '/api/public/export'
      fullPath: '/api/public/export'
      preLoaderRoute: typeof ApiPublicExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  ProgramsRoute: ProgramsRoute,
  StatsRoute: StatsRoute,
  UpdatesRoute: UpdatesRoute,
  DocsApiKeyRoute: DocsApiKeyRoute,
  DocsFetchSubdomainsRoute: DocsFetchSubdomainsRoute,
  DomainDomainRoute: DomainDomainRoute,
  ProgramSlugRoute: ProgramSlugRoute,
  ApiPublicExportRoute: ApiPublicExportRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
