/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as Chaos_updatesRouteImport } from './routes/chaos_updates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LivemapRouteImport } from './routes/livemap'
import { Route as LivesubsRouteImport } from './routes/livesubs'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RecentsubsRouteImport } from './routes/recentsubs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as DocsApiKeyRouteImport } from './routes/docs/api-key'
import { Route as DocsFetchSubdomainsRouteImport } from './routes/docs/fetch-subdomains'
import { Route as DomainDomainRouteImport } from './routes/domain.$domain'
import { Route as ProgramSlugRouteImport } from './routes/program.$slug'
import { Route as RawSplatRouteImport } from './routes/raw.$'
import { Route as ApiPublicExportRouteImport } from './routes/api/public/export'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as DocsApiIndexRouteImport } from './routes/docs/api.index'
import { Route as DocsApiAuthenticationRouteImport } from './routes/docs/api.authentication'
import { Route as DocsApiChangelogRouteImport } from './routes/docs/api.changelog'
import { Route as DocsApiErrorsRouteImport } from './routes/docs/api.errors'
import { Route as DocsApiGuidesRouteImport } from './routes/docs/api.guides'
import { Route as DocsApiLiveRouteImport } from './routes/docs/api.live'
import { Route as DocsApiPaginationRouteImport } from './routes/docs/api.pagination'
import { Route as DocsApiQuickstartRouteImport } from './routes/docs/api.quickstart'
import { Route as DocsApiRawRouteImport } from './routes/docs/api.raw'
import { Route as ApiPublicHooksProbeRouteImport } from './routes/api/public/hooks/probe'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'
import { Route as ApiPublicRawSplatRouteImport } from './routes/api/public/raw/$'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as DocsApiReferenceEndpointRouteImport } from './routes/docs/api.reference.$endpoint'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Chaos_updatesRoute = Chaos_updatesRouteImport.update({
  id: '/chaos_updates',
  path: '/chaos_updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LivemapRoute = LivemapRouteImport.update({
  id: '/livemap',
  path: '/livemap',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesubsRoute = LivesubsRouteImport.update({
  id: '/livesubs',
  path: '/livesubs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentsubsRoute = RecentsubsRouteImport.update({
  id: '/recentsubs',
  path: '/recentsubs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiKeyRoute = DocsApiKeyRouteImport.update({
  id: '/docs/api-key',
  path: '/docs/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFetchSubdomainsRoute = DocsFetchSubdomainsRouteImport.update({
  id: '/docs/fetch-subdomains',
  path: '/docs/fetch-subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainRoute = DomainDomainRouteImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSlugRoute = ProgramSlugRouteImport.update({
  id: '/program/$slug',
  path: '/program/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RawSplatRoute = RawSplatRouteImport.update({
  id: '/raw/$',
  path: '/raw/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportRoute = ApiPublicExportRouteImport.update({
  id: '/api/public/export',
  path: '/api/public/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiIndexRoute = DocsApiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiAuthenticationRoute = DocsApiAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiChangelogRoute = DocsApiChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiErrorsRoute = DocsApiErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiGuidesRoute = DocsApiGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiLiveRoute = DocsApiLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiPaginationRoute = DocsApiPaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiQuickstartRoute = DocsApiQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsApiRoute,
} as any)
const DocsApiRawRoute = DocsApiRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => DocsApiRoute,
} as any)
const ApiPublicHooksProbeRoute = ApiPublicHooksProbeRouteImport.update({
  id: '/api/public/hooks/probe',
  path: '/api/public/hooks/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRawSplatRoute = ApiPublicRawSplatRouteImport.update({
  id: '/api/public/raw/$',
  path: '/api/public/raw/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiReferenceEndpointRoute =
  DocsApiReferenceEndpointRouteImport.update({
    id: '/reference/$endpoint',
    path: '/reference/$endpoint',
    getParentRoute: () => DocsApiRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/chaos_updates': typeof Chaos_updatesRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/livemap': typeof LivemapRoute
  '/livesubs': typeof LivesubsRoute
  '/new': typeof NewRoute
  '/notes': typeof NotesRoute
  '/programs': typeof ProgramsRoute
  '/queue': typeof QueueRoute
  '/recentsubs': typeof RecentsubsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/docs/api': typeof DocsApiRouteWithChildren
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/raw/$': typeof RawSplatRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/docs/api/authentication': typeof DocsApiAuthenticationRoute
  '/docs/api/changelog': typeof DocsApiChangelogRoute
  '/docs/api/errors': typeof DocsApiErrorsRoute
  '/docs/api/guides': typeof DocsApiGuidesRoute
  '/docs/api/live': typeof DocsApiLiveRoute
  '/docs/api/pagination': typeof DocsApiPaginationRoute
  '/docs/api/quickstart': typeof DocsApiQuickstartRoute
  '/docs/api/raw': typeof DocsApiRawRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/api/public/hooks/probe': typeof ApiPublicHooksProbeRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/raw/$': typeof ApiPublicRawSplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/docs/api/reference/$endpoint': typeof DocsApiReferenceEndpointRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/chaos_updates': typeof Chaos_updatesRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/livemap': typeof LivemapRoute
  '/livesubs': typeof LivesubsRoute
  '/new': typeof NewRoute
  '/notes': typeof NotesRoute
  '/programs': typeof ProgramsRoute
  '/queue': typeof QueueRoute
  '/recentsubs': typeof RecentsubsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/raw/$': typeof RawSplatRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/docs/api/authentication': typeof DocsApiAuthenticationRoute
  '/docs/api/changelog': typeof DocsApiChangelogRoute
  '/docs/api/errors': typeof DocsApiErrorsRoute
  '/docs/api/guides': typeof DocsApiGuidesRoute
  '/docs/api/live': typeof DocsApiLiveRoute
  '/docs/api/pagination': typeof DocsApiPaginationRoute
  '/docs/api/quickstart': typeof DocsApiQuickstartRoute
  '/docs/api/raw': typeof DocsApiRawRoute
  '/docs/api': typeof DocsApiIndexRoute
  '/api/public/hooks/probe': typeof ApiPublicHooksProbeRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/raw/$': typeof ApiPublicRawSplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/docs/api/reference/$endpoint': typeof DocsApiReferenceEndpointRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/chaos_updates': typeof Chaos_updatesRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/livemap': typeof LivemapRoute
  '/livesubs': typeof LivesubsRoute
  '/new': typeof NewRoute
  '/notes': typeof NotesRoute
  '/programs': typeof ProgramsRoute
  '/queue': typeof QueueRoute
  '/recentsubs': typeof RecentsubsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/docs/api': typeof DocsApiRouteWithChildren
  '/docs/api-key': typeof DocsApiKeyRoute
  '/docs/fetch-subdomains': typeof DocsFetchSubdomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/raw/$': typeof RawSplatRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/docs/api/authentication': typeof DocsApiAuthenticationRoute
  '/docs/api/changelog': typeof DocsApiChangelogRoute
  '/docs/api/errors': typeof DocsApiErrorsRoute
  '/docs/api/guides': typeof DocsApiGuidesRoute
  '/docs/api/live': typeof DocsApiLiveRoute
  '/docs/api/pagination': typeof DocsApiPaginationRoute
  '/docs/api/quickstart': typeof DocsApiQuickstartRoute
  '/docs/api/raw': typeof DocsApiRawRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/api/public/hooks/probe': typeof ApiPublicHooksProbeRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/raw/$': typeof ApiPublicRawSplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/docs/api/reference/$endpoint': typeof DocsApiReferenceEndpointRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/alerts'
    | '/auth'
    | '/chaos_updates'
    | '/dashboard'
    | '/live'
    | '/livemap'
    | '/livesubs'
    | '/new'
    | '/notes'
    | '/programs'
    | '/queue'
    | '/recentsubs'
    | '/sitemap.xml'
    | '/stats'
    | '/updates'
    | '/docs/api'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/domain/$domain'
    | '/program/$slug'
    | '/raw/$'
    | '/api/public/export'
    | '/api/v1/$'
    | '/docs/api/authentication'
    | '/docs/api/changelog'
    | '/docs/api/errors'
    | '/docs/api/guides'
    | '/docs/api/live'
    | '/docs/api/pagination'
    | '/docs/api/quickstart'
    | '/docs/api/raw'
    | '/docs/api/'
    | '/api/public/hooks/probe'
    | '/api/public/hooks/scan'
    | '/api/public/raw/$'
    | '/api/public/v1/$'
    | '/docs/api/reference/$endpoint'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/alerts'
    | '/auth'
    | '/chaos_updates'
    | '/dashboard'
    | '/live'
    | '/livemap'
    | '/livesubs'
    | '/new'
    | '/notes'
    | '/programs'
    | '/queue'
    | '/recentsubs'
    | '/sitemap.xml'
    | '/stats'
    | '/updates'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/domain/$domain'
    | '/program/$slug'
    | '/raw/$'
    | '/api/public/export'
    | '/api/v1/$'
    | '/docs/api/authentication'
    | '/docs/api/changelog'
    | '/docs/api/errors'
    | '/docs/api/guides'
    | '/docs/api/live'
    | '/docs/api/pagination'
    | '/docs/api/quickstart'
    | '/docs/api/raw'
    | '/docs/api'
    | '/api/public/hooks/probe'
    | '/api/public/hooks/scan'
    | '/api/public/raw/$'
    | '/api/public/v1/$'
    | '/docs/api/reference/$endpoint'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/alerts'
    | '/auth'
    | '/chaos_updates'
    | '/dashboard'
    | '/live'
    | '/livemap'
    | '/livesubs'
    | '/new'
    | '/notes'
    | '/programs'
    | '/queue'
    | '/recentsubs'
    | '/sitemap.xml'
    | '/stats'
    | '/updates'
    | '/docs/api'
    | '/docs/api-key'
    | '/docs/fetch-subdomains'
    | '/domain/$domain'
    | '/program/$slug'
    | '/raw/$'
    | '/api/public/export'
    | '/api/v1/$'
    | '/docs/api/authentication'
    | '/docs/api/changelog'
    | '/docs/api/errors'
    | '/docs/api/guides'
    | '/docs/api/live'
    | '/docs/api/pagination'
    | '/docs/api/quickstart'
    | '/docs/api/raw'
    | '/docs/api/'
    | '/api/public/hooks/probe'
    | '/api/public/hooks/scan'
    | '/api/public/raw/$'
    | '/api/public/v1/$'
    | '/docs/api/reference/$endpoint'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  Chaos_updatesRoute: typeof Chaos_updatesRoute
  DashboardRoute: typeof DashboardRoute
  LiveRoute: typeof LiveRoute
  LivemapRoute: typeof LivemapRoute
  LivesubsRoute: typeof LivesubsRoute
  NewRoute: typeof NewRoute
  NotesRoute: typeof NotesRoute
  ProgramsRoute: typeof ProgramsRoute
  QueueRoute: typeof QueueRoute
  RecentsubsRoute: typeof RecentsubsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  UpdatesRoute: typeof UpdatesRoute
  DocsApiRoute: typeof DocsApiRouteWithChildren
  DocsApiKeyRoute: typeof DocsApiKeyRoute
  DocsFetchSubdomainsRoute: typeof DocsFetchSubdomainsRoute
  DomainDomainRoute: typeof DomainDomainRoute
  ProgramSlugRoute: typeof ProgramSlugRoute
  RawSplatRoute: typeof RawSplatRoute
  ApiPublicExportRoute: typeof ApiPublicExportRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicHooksProbeRoute: typeof ApiPublicHooksProbeRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
  ApiPublicRawSplatRoute: typeof ApiPublicRawSplatRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaos_updates': {
      id: '/chaos_updates'
      path: '/chaos_updates'
      fullPath: '/chaos_updates'
      preLoaderRoute: typeof Chaos_updatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livemap': {
      id: '/livemap'
      path: '/livemap'
      fullPath: '/livemap'
      preLoaderRoute: typeof LivemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livesubs': {
      id: '/livesubs'
      path: '/livesubs'
      fullPath: '/livesubs'
      preLoaderRoute: typeof LivesubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recentsubs': {
      id: '/recentsubs'
      path: '/recentsubs'
      fullPath: '/recentsubs'
      preLoaderRoute: typeof RecentsubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-key': {
      id: '/docs/api-key'
      path: '/docs/api-key'
      fullPath: '/docs/api-key'
      preLoaderRoute: typeof DocsApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/fetch-subdomains': {
      id: '/docs/fetch-subdomains'
      path: '/docs/fetch-subdomains'
      fullPath: '/docs/fetch-subdomains'
      preLoaderRoute: typeof DocsFetchSubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$slug': {
      id: '/program/$slug'
      path: '/program/$slug'
      fullPath: '/program/$slug'
      preLoaderRoute: typeof ProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/$': {
      id: '/raw/$'
      path: '/raw/$'
      fullPath: '/raw/$'
      preLoaderRoute: typeof RawSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/export': {
      id: '/api/public/export'
      path: '/api/public/export'
      fullPath: '/api/public/export'
      preLoaderRoute: typeof ApiPublicExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/': {
      id: '/docs/api/'
      path: '/'
      fullPath: '/docs/api/'
      preLoaderRoute: typeof DocsApiIndexRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/authentication': {
      id: '/docs/api/authentication'
      path: '/authentication'
      fullPath: '/docs/api/authentication'
      preLoaderRoute: typeof DocsApiAuthenticationRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/changelog': {
      id: '/docs/api/changelog'
      path: '/changelog'
      fullPath: '/docs/api/changelog'
      preLoaderRoute: typeof DocsApiChangelogRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/errors': {
      id: '/docs/api/errors'
      path: '/errors'
      fullPath: '/docs/api/errors'
      preLoaderRoute: typeof DocsApiErrorsRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/guides': {
      id: '/docs/api/guides'
      path: '/guides'
      fullPath: '/docs/api/guides'
      preLoaderRoute: typeof DocsApiGuidesRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/live': {
      id: '/docs/api/live'
      path: '/live'
      fullPath: '/docs/api/live'
      preLoaderRoute: typeof DocsApiLiveRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/pagination': {
      id: '/docs/api/pagination'
      path: '/pagination'
      fullPath: '/docs/api/pagination'
      preLoaderRoute: typeof DocsApiPaginationRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/quickstart': {
      id: '/docs/api/quickstart'
      path: '/quickstart'
      fullPath: '/docs/api/quickstart'
      preLoaderRoute: typeof DocsApiQuickstartRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/docs/api/raw': {
      id: '/docs/api/raw'
      path: '/raw'
      fullPath: '/docs/api/raw'
      preLoaderRoute: typeof DocsApiRawRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/api/public/hooks/probe': {
      id: '/api/public/hooks/probe'
      path: '/api/public/hooks/probe'
      fullPath: '/api/public/hooks/probe'
      preLoaderRoute: typeof ApiPublicHooksProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/raw/$': {
      id: '/api/public/raw/$'
      path: '/api/public/raw/$'
      fullPath: '/api/public/raw/$'
      preLoaderRoute: typeof ApiPublicRawSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/reference/$endpoint': {
      id: '/docs/api/reference/$endpoint'
      path: '/reference/$endpoint'
      fullPath: '/docs/api/reference/$endpoint'
      preLoaderRoute: typeof DocsApiReferenceEndpointRouteImport
      parentRoute: typeof DocsApiRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsApiRouteChildren {
  DocsApiAuthenticationRoute: typeof DocsApiAuthenticationRoute
  DocsApiChangelogRoute: typeof DocsApiChangelogRoute
  DocsApiErrorsRoute: typeof DocsApiErrorsRoute
  DocsApiGuidesRoute: typeof DocsApiGuidesRoute
  DocsApiLiveRoute: typeof DocsApiLiveRoute
  DocsApiPaginationRoute: typeof DocsApiPaginationRoute
  DocsApiQuickstartRoute: typeof DocsApiQuickstartRoute
  DocsApiRawRoute: typeof DocsApiRawRoute
  DocsApiIndexRoute: typeof DocsApiIndexRoute
  DocsApiReferenceEndpointRoute: typeof DocsApiReferenceEndpointRoute
}

const DocsApiRouteChildren: DocsApiRouteChildren = {
  DocsApiAuthenticationRoute: DocsApiAuthenticationRoute,
  DocsApiChangelogRoute: DocsApiChangelogRoute,
  DocsApiErrorsRoute: DocsApiErrorsRoute,
  DocsApiGuidesRoute: DocsApiGuidesRoute,
  DocsApiLiveRoute: DocsApiLiveRoute,
  DocsApiPaginationRoute: DocsApiPaginationRoute,
  DocsApiQuickstartRoute: DocsApiQuickstartRoute,
  DocsApiRawRoute: DocsApiRawRoute,
  DocsApiIndexRoute: DocsApiIndexRoute,
  DocsApiReferenceEndpointRoute: DocsApiReferenceEndpointRoute,
}

const DocsApiRouteWithChildren =
  DocsApiRoute._addFileChildren(DocsApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  Chaos_updatesRoute: Chaos_updatesRoute,
  DashboardRoute: DashboardRoute,
  LiveRoute: LiveRoute,
  LivemapRoute: LivemapRoute,
  LivesubsRoute: LivesubsRoute,
  NewRoute: NewRoute,
  NotesRoute: NotesRoute,
  ProgramsRoute: ProgramsRoute,
  QueueRoute: QueueRoute,
  RecentsubsRoute: RecentsubsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  UpdatesRoute: UpdatesRoute,
  DocsApiRoute: DocsApiRouteWithChildren,
  DocsApiKeyRoute: DocsApiKeyRoute,
  DocsFetchSubdomainsRoute: DocsFetchSubdomainsRoute,
  DomainDomainRoute: DomainDomainRoute,
  ProgramSlugRoute: ProgramSlugRoute,
  RawSplatRoute: RawSplatRoute,
  ApiPublicExportRoute: ApiPublicExportRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicHooksProbeRoute: ApiPublicHooksProbeRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
  ApiPublicRawSplatRoute: ApiPublicRawSplatRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
